# Generated by Django 6.0.4 on 2026-04-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='cashier',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'បានបើក'), ('paid', 'បានបង់'), ('refunded', 'បានសង'), ('cancelled', 'បានលុបចោល')], default='open', max_length=20),
        ),
    ]
