# Generated by Django 6.0.4 on 2026-05-12 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'មិនទាន់បង់'), ('paid', 'បានបង់'), ('refunded', 'បានសង'), ('cancelled', 'បានលុបចោល')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product'),
        ),
    ]
