# Generated by Django 6.0.4 on 2026-05-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_order_status_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unpaid', 'មិនទាន់បង់'), ('paid', 'បានបង់'), ('refunded', 'បានសង'), ('cancelled', 'បានលុបចោល')], default='paid', max_length=20),
        ),
    ]
